# Generated by Django 5.0.6 on 2024-06-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=25)),
                ('last_name', models.CharField(blank=True, max_length=35)),
                ('birth_date', models.DateField(blank=True)),
                ('main_photo', models.FilePathField(blank=True)),
                ('about_me', models.TextField(blank=True)),
            ],
        ),
    ]
